
[env]
TERM = "alacritty"

[window]
opacity = 1.0
startup_mode = "Windowed"
decorations = "Buttonless"
padding = { x = 15, y = 15 }

[font]
normal = { family = "MesloLGS Nerd Font Mono"}
bold = { family = "MesloLGS Nerd Font Mono"}
italic = { family = "MesloLGS Nerd Font Mono"}
size = 16.0

[selection]
save_to_clipboard = true
